"""watchlist item remove position

Revision ID: 2ce8c6a09c51
Revises: f0add0fd7c4e
Create Date: 2026-04-07 08:00:13.583143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ce8c6a09c51'
down_revision: Union[str, Sequence[str], None] = 'f0add0fd7c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('watchlist_item_position_key'), 'watchlist_item', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('watchlist_item_position_key'), 'watchlist_item', ['position'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
