"""extend watchlist item

Revision ID: 8f939ad9ae2f
Revises: 32bd88c5e8b0
Create Date: 2026-05-12 10:55:21.190336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f939ad9ae2f'
down_revision: Union[str, Sequence[str], None] = '32bd88c5e8b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watchlist_item', sa.Column('total_episodes', sa.Integer(), nullable=True))
    op.add_column('watchlist_item', sa.Column('current_episode', sa.Integer(), nullable=True))
    op.add_column('watchlist_item', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('watchlist_item', sa.Column('genres', sa.String(length=255), nullable=True))
    op.add_column('watchlist_item', sa.Column('media_type', sa.String(length=20), nullable=True))
    op.alter_column('watchlist_item', 'position',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.String(length=50),
               existing_nullable=False,
               postgresql_using='position::text')
    op.drop_constraint('watchlist_item_mal_id_key', 'watchlist_item', type_='unique')
    op.create_unique_constraint('uq_watchlist_user_mal', 'watchlist_item', ['user_id', 'mal_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_watchlist_user_mal', 'watchlist_item', type_='unique')
    op.create_unique_constraint(op.f('watchlist_item_mal_id_key'), 'watchlist_item', ['mal_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('watchlist_item', 'position',
               existing_type=sa.String(length=50),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False)
    op.drop_column('watchlist_item', 'media_type')
    op.drop_column('watchlist_item', 'genres')
    op.drop_column('watchlist_item', 'score')
    op.drop_column('watchlist_item', 'current_episode')
    op.drop_column('watchlist_item', 'total_episodes')
    # ### end Alembic commands ###
