"""add watchlist table

Revision ID: f0add0fd7c4e
Revises: 0abffddaa0ea
Create Date: 2026-04-07 06:58:43.694746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0add0fd7c4e'
down_revision: Union[str, Sequence[str], None] = '0abffddaa0ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('watchlist_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('mal_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.Column('mal_url', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('WATCH', 'WATCHING', 'WATCHED', name='watchstatus'), nullable=False),
    sa.Column('position', sa.Float(), nullable=False),
    sa.Column('added_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mal_id'),
    sa.UniqueConstraint('position')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('watchlist_item')
    # ### end Alembic commands ###
