# Generated by Django 3.1.7 on 2021-03-10 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WatchlistItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('image_url', models.URLField()),
                ('mal_url', models.URLField()),
                ('type', models.CharField(choices=[('anime', 'Anime'), ('manga', 'Manga')], default='anime', max_length=5)),
                ('status', models.CharField(choices=[('watch', 'Watch'), ('watching', 'Watching'), ('watched', 'Watched')], default='watch', max_length=8)),
            ],
        ),
    ]
