# Generated by Django 3.1.7 on 2021-04-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist', '0002_watchlistitem_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistitem',
            name='next_item_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
